# Generated by Django 5.2.16 on 2026-07-22 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Graph",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("article_id", models.CharField(blank=True, default="", max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("edge_id", models.CharField(max_length=200)),
                (
                    "edge_class",
                    models.CharField(
                        choices=[("relation", "Relation"), ("cross_reference", "Cross reference")], max_length=20
                    ),
                ),
                ("subject_id", models.CharField(max_length=200)),
                ("predicate", models.CharField(max_length=32)),
                ("object_ref", models.CharField(max_length=400)),
                ("subject_type", models.CharField(blank=True, default="", max_length=16)),
                ("object_type", models.CharField(blank=True, default="", max_length=16)),
                ("data", models.JSONField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="edges", to="graphs.graph"
                    ),
                ),
            ],
            options={
                "ordering": ["graph", "edge_class", "edge_id"],
                "indexes": [
                    models.Index(fields=["graph", "subject_id"], name="graphs_edge_graph_i_009041_idx"),
                    models.Index(fields=["graph", "object_ref"], name="graphs_edge_graph_i_b4a98a_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("graph", "edge_id"), name="uniq_edge_per_graph")],
            },
        ),
        migrations.CreateModel(
            name="Node",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("node_id", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("statement", "Statement"), ("evidence", "Evidence"), ("activity", "Activity")],
                        max_length=16,
                    ),
                ),
                ("stype", models.CharField(blank=True, default="", max_length=32)),
                ("status", models.CharField(blank=True, default="", max_length=32)),
                ("text", models.TextField(blank=True, default="")),
                ("data", models.JSONField()),
                (
                    "graph",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="nodes", to="graphs.graph"
                    ),
                ),
            ],
            options={
                "ordering": ["graph", "kind", "node_id"],
                "indexes": [
                    models.Index(fields=["graph", "kind"], name="graphs_node_graph_i_cf857e_idx"),
                    models.Index(fields=["graph", "status"], name="graphs_node_graph_i_5d2c56_idx"),
                ],
                "constraints": [models.UniqueConstraint(fields=("graph", "node_id"), name="uniq_node_per_graph")],
            },
        ),
    ]
